# Generated by Django 5.0.2 on 2024-03-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_hotel_country_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='number_of_people',
            new_name='adults',
        ),
        migrations.RemoveField(
            model_name='room',
            name='maximum_occupancy',
        ),
        migrations.AddField(
            model_name='booking',
            name='children',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='features',
            field=models.ManyToManyField(through='polls.SpecificHotelFeature', to='polls.hotelfeatures'),
        ),
        migrations.AddField(
            model_name='room',
            name='adults',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='children',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending'),
        ),
    ]
