# Generated by Django 5.0.2 on 2024-02-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_roomtype_alter_room_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed')], default='Pending'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='maximum_occupancy',
            field=models.IntegerField(default=1),
        ),
    ]
