# Generated by Django 5.0.3 on 2024-03-11 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='city',
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.province'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending'),
        ),
    ]
