# Generated by Django 5.0.3 on 2024-03-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], default='Pending'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
