# Generated by Django 5.0.3 on 2024-03-23 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='province',
        ),
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.city'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending'),
        ),
    ]
